name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Determine dependencies
        run: |
          cat package.json | jq -c '{dependencies: .dependencies, peerDependencies: .peerDependencies, devDependencies: .devDependencies }' > dependencies.json
          cat dependencies.json | jq

      - name: Load dependency cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('dependencies.json') }}

      - name: Install dependencies
        run: npm install --ignore-scripts --no-audit

      - name: Test
        run: npm run test
